MetalMockTests\Debug\MetalMockTests.exe
MetalMockExamples\Debug\MetalMockExamples.exe
ZenUnitLibraryTests\Debug\ZenUnitLibraryTests.exe
ZenUnitUtilsAndAssertionTests\Debug\ZenUnitUtilsAndAssertionTests.exe
ZenUnitExamples\Debug\ZenUnitExamples.exe
