#pragma once

#include "ZenUnit/ZenUnit.h"

#include "ZenMock/0/ZENMOCK_NONVOID0.h"
#include "ZenMock/0/ZENMOCK_VOID0.h"
#include "ZenMock/0/ZeroArgumentMocker.h"

#include "ZenMock/1/OneArgumentCall.h"
#include "ZenMock/1/OneArgumentCallRef.h"
#include "ZenMock/1/OneArgumentMocker.h"
#include "ZenMock/1/ZENMOCK_NONVOID1.h"
#include "ZenMock/1/ZENMOCK_VOID1.h"

#include "ZenMock/2/TwoArgumentCall.h"
#include "ZenMock/2/TwoArgumentCallRef.h"
#include "ZenMock/2/TwoArgumentMocker.h"
#include "ZenMock/2/ZENMOCK_NONVOID2.h"
#include "ZenMock/2/ZENMOCK_VOID2.h"

#include "ZenMock/3/ThreeArgumentCall.h"
#include "ZenMock/3/ThreeArgumentCallRef.h"
#include "ZenMock/3/ThreeArgumentMocker.h"
#include "ZenMock/3/ZENMOCK_NONVOID3.h"
#include "ZenMock/3/ZENMOCK_VOID3.h"

#include "ZenMock/4/FourArgumentCall.h"
#include "ZenMock/4/FourArgumentCallRef.h"
#include "ZenMock/4/FourArgumentMocker.h"
#include "ZenMock/4/ZENMOCK_NONVOID4.h"
#include "ZenMock/4/ZENMOCK_VOID4.h"

#include "ZenMock/5/FiveArgumentCall.h"
#include "ZenMock/5/FiveArgumentCallRef.h"
#include "ZenMock/5/FiveArgumentMocker.h"
#include "ZenMock/5/ZENMOCK_NONVOID5.h"
#include "ZenMock/5/ZENMOCK_VOID5.h"

#include "ZenMock/6/SixArgumentCall.h"
#include "ZenMock/6/SixArgumentCallRef.h"
#include "ZenMock/6/SixArgumentMocker.h"
#include "ZenMock/6/ZENMOCK_NONVOID6.h"
#include "ZenMock/6/ZENMOCK_VOID6.h"

#include "ZenMock/7/SevenArgumentCall.h"
#include "ZenMock/7/SevenArgumentCallRef.h"
#include "ZenMock/7/SevenArgumentMocker.h"
#include "ZenMock/7/ZENMOCK_NONVOID7.h"
#include "ZenMock/7/ZENMOCK_VOID7.h"

#include "ZenMock/8/EightArgumentCall.h"
#include "ZenMock/8/EightArgumentCallRef.h"
#include "ZenMock/8/EightArgumentMocker.h"
#include "ZenMock/8/ZENMOCK_NONVOID8.h"
#include "ZenMock/8/ZENMOCK_VOID8.h"

#include "ZenMock/9/NineArgumentCall.h"
#include "ZenMock/9/NineArgumentCallRef.h"
#include "ZenMock/9/NineArgumentMocker.h"
#include "ZenMock/9/ZENMOCK_NONVOID9.h"
#include "ZenMock/9/ZENMOCK_VOID9.h"

#include "ZenMock/10/TenArgumentCall.h"
#include "ZenMock/10/TenArgumentCallRef.h"
#include "ZenMock/10/TenArgumentMocker.h"
#include "ZenMock/10/ZENMOCK_NONVOID10.h"
#include "ZenMock/10/ZENMOCK_VOID10.h"

#include "ZenMock/Exceptions/ExceptionThrower.h"
#include "ZenMock/Exceptions/FunctionAlreadyExpectedException.h"
#include "ZenMock/Exceptions/FunctionAlreadyExpectedException.cpp"
#include "ZenMock/Exceptions/ReturnValueMustBeSpecifiedException.h"
#include "ZenMock/Exceptions/ReturnValueMustBeSpecifiedException.cpp"
#include "ZenMock/Exceptions/TemplateThrowable.h"
#include "ZenMock/Exceptions/Throwable.h"
#include "ZenMock/Exceptions/UnexpectedCallException.h"
#include "ZenMock/Exceptions/UnsupportedAssertCalledZeroTimesException.h"
#include "ZenMock/Exceptions/UnsupportedAssertCalledZeroTimesException.cpp"

#include "ZenMock/Mock.h"
#include "ZenMock/Signature.h"
#include "ZenMock/ValueReturner.h"
#include "ZenMock/ZEN.h"
#include "ZenMock/ZENAssertionToken.h"
#include "ZenMock/ZenMocker.h"
