name: ZenUnitAndMetalMock
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cxx: [clang++, g++]
        cmake_build_type: [Debug, RelWithDebInfo]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          
      - name: Download LinuxCPlusPlusBuilder
        uses: dawidd6/action-download-artifact@v9
        with:
          repo: NeilJustice/LinuxCPlusPlusBuilder
          github_token: ${{ secrets.CSHARP_AND_CPLUSPLUS_BUILDERS_READ_PAT }}
          workflow_search: true
          workflow_conclusion: success
          name: LinuxCPlusPlusBuilder
          use_unzip: true
          path: LinuxCPlusPlusBuilder/

      - name: Download ZenUnit.h and MetalMock.h
        run: |
          curl https://raw.githubusercontent.com/NeilJustice/ZenUnitAndMetalMock/main/ZenUnitAndMetalMock/ZenUnit.h --create-dirs -o "$GITHUB_WORKSPACE/ZenUnitAndMetalMock/ZenUnit.h"
          curl https://raw.githubusercontent.com/NeilJustice/ZenUnitAndMetalMock/main/ZenUnitAndMetalMock/MetalMock.h --create-dirs -o "$GITHUB_WORKSPACE/ZenUnitAndMetalMock/MetalMock.h"
        
      - name: Install lld, ninja-build, and libtbb-dev
        run: sudo apt-get install lld ninja-build libtbb-dev
        
      - name: Install lcov Perl dependencies if g++ Release
        run: sudo apt-get install libcapture-tiny-perl libdatetime-perl
        if: ${{ matrix.cxx == 'g++' && matrix.cmake_build_type == 'Release' }}
          
      - name: Prebuild tree $GITHUB_WORKSPACE
        run: tree $GITHUB_WORKSPACE
        
      - name: Build with LinuxCPlusPlusBuilder in non-code-coverage mode if Clang Debug, Clang RelWithDebInfo, or GCC Debug
        run: |
          LinuxCPlusPlusBuilder/LinuxCPlusPlusBuilder build-cpp-solution \
            --solution-name=ZenUnitAndMetalMock \
            --configuration="${{ matrix.cmake_build_type }}" \
            --cmake-definitions="-DFastLinuxDebugBuildMode=ON -DFastLinuxReleaseBuildMode=ON" \
            --install=false
        env:
          CXX: "/usr/bin/${{ matrix.cxx }}"
        if: ${{ matrix.cxx == 'clang++' || (matrix.cxx == 'g++' && matrix.cmake_build_type == 'Debug') }}

      - name: Build with LinuxCPlusPlusBuilder in code coverage mode if GCC RelWithDebInfo
        run: |
           LinuxCPlusPlusBuilder/LinuxCPlusPlusBuilder build-cpp-solution \
             --solution-name=ZenUnitAndMetalMock \
             --configuration=RelWithDebInfo \
             --cmake-definitions="-DLCovCodeCoverageMode=ON" \
             --install=false
        env:
          CXX: "/usr/bin/${{ matrix.cxx }}"
        if: ${{ matrix.cxx == 'g++' && matrix.cmake_build_type == 'RelWithDebInfo' }}

      - name: Install and run lcov 2.5 then upload to Codecov.io if g++ Release
        run: |
          mkdir -p lcov_2.5
          wget https://github.com/linux-test-project/lcov/releases/download/v2.5/lcov-2.5.tar.gz --output-document="lcov_2.5/lcov-2.5.tar.gz"
          tar xf "lcov_2.5/lcov-2.5.tar.gz" --strip-components=1 --directory lcov_2.5
          lcov_2.5/bin/lcov --version
          lcov_2.5/bin/lcov --directory . --capture --no-external --ignore-errors inconsistent --output-file coverage.info
          lcov_2.5/bin/lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info -t ${{ secrets.CODECOV_TOKEN }} || echo "Codecov did not collect coverage reports"
        if: ${{ matrix.cxx == 'g++' && matrix.cmake_build_type == 'Release' }}

      - name: Print .comment section of binary libZenUnitAndMetalMockTests to confirm it was linked with LLD
        run: readelf --string-dump .comment "${{matrix.cmake_build_type}}/libZenUnitAndMetalMockTests/libZenUnitAndMetalMockTests"

      - name: Postbuild tree $GITHUB_WORKSPACE
        run: tree $GITHUB_WORKSPACE
