#!/bin/bash
set -ev

cppcheck \
   --enable=all \
   -DCOMMA \
   -DTEST \
   -DTESTS \
   -DAFACT \
   -DFACTS \
   -DTEST1X1 \
   -DTEST2X2 \
   -DTEST3X3 \
   -DTEST4X4 \
   -DTEST5X5 \
   -DTEST6X6 \
   -DTEST7X7 \
   -DTEST8X8 \
   -DTEST9X9 \
   -DTEST10X10 \
   -DRUN_TESTS \
   -DRUN_TEMPLATE_TESTS \
   -DMETALMOCK_VOID0_FREE \
   -DMETALMOCK_VOID1_FREE \
   -DMETALMOCK_VOID2_FREE \
   -DMETALMOCK_NONVOID0_STATIC \
   -DMETALMOCK_NONVOID1_FREE \
   -DMETALMOCK_NONVOID1_STATIC \
   -DMETALMOCK_NONVOID3_CONST \
   -I . \
   -I ZenUnitTestUtils \
   -j 64 \
   .

